dist: xenial

sudo: false
language: node_js
node_js:
  - '10'
install:
  - npm run phoenix -- --no-progress
script:
  - npm run lint
  - npm run test:ci

jobs:
  include:
    - stage: Release
      if: type = pull_request
      script:
        - sh .travis-release.sh